name: Build

on:
  push:
    branches: [ "build" ]

env:
  BUILD_TYPE: Release

jobs:
  Win64:
    runs-on: windows-2019
    steps:

    - uses: actions/checkout@v3

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Install vcpkg
      uses: lukka/run-vcpkg@v10.7
      with:
        vcpkgGitCommitId: 401b26c9866a071f645ae57831caa419b2c48be1

    - name: Install dependencies
      run: |
        vcpkg install --triplet x64-windows

    - name: List files
      run: Get-ChildItem -Recurse "vcpkg"
        
    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
